plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'gr.pantelis.dvbtv'
    compileSdk 34

    defaultConfig {
        applicationId 'gr.pantelis.dvbtv'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '0.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation project(':drivers')
    implementation project(':rtlsdr')
    implementation project(':sdrdrivertools')
    implementation 'org.videolan.android:libvlc-all:3.6.0'
}
